export { default as Loading } from './common/Loading'
export { default as Section } from './common/Section'
export { default as InputForm } from './inputs/InputForm'
export { default as Button } from './common/Button'
export { default as Header } from './header/Header'
export { default as Banner } from './banner/Banner'
export { default as Card } from './posts/Card'
